import { defineReel } from "../../spec/define";

/**
 * STYLE DEMO — витрина всех компонентов. Не для публикации.
 * Открой в Studio (Lab → style-demo), чтобы увидеть, как выглядит каждый
 * инструмент, и скопировать нужный кусок в свой рилс.
 */
export default defineReel({
  id: "style-demo",
  title: "Style demo — все компоненты",
  look: { grain: true },
  audioCuts: [{ from: 16.0, to: 17.2 }],
  captions: {
    // mode "words": слова появляются по одному, *ключевое* — крупнее (keyScale).
    // mode "lines" (по умолчанию): вся строка сразу.
    mode: "words",
    style: "box",
    lines: [
      { text: "субтитры для *войсовера*", start: 2.2, end: 3.4 },
      { text: "короткими [кусками]", start: 3.4, end: 4.6 },
      { text: "это субтитры *по слову*", start: 31.9, end: 33.4 },
      { text: "ключевое слово", start: 33.4, end: 34.2 },
      { text: "*крупнее*", start: 34.2, end: 34.9 },
    ],
  },
  scenes: [
    {
      type: "text",
      note: "slam",
      kicker: "01 / text: slam",
      lines: ["Я сделала", "*приложение*"],
      bg: "paper",
      duration: 2.0,
      sfx: [{ at: 0, sfx: "thud", volume: 0.7 }],
    },
    {
      type: "text",
      note: "words + orange bg",
      kicker: "02 / text: words",
      lines: ["без опыта", "в [программировании]", "_и почти без сна_"],
      animate: "words",
      bg: "orange",
      duration: 2.6,
      transition: "flash",
    },
    {
      type: "text",
      note: "typewriter on ink",
      kicker: "03 / text: type",
      lines: ["> npm run", "  fix-my-life", "*ERROR*"],
      animate: "type",
      font: "mono",
      size: 92,
      bg: "ink",
      duration: 2.4,
      transition: "glitch",
      sfx: [{ at: 0.05, sfx: "typing", volume: 0.5, duration: 1.2 }, { at: 1.5, sfx: "error", volume: 0.5 }],
    },
    {
      type: "video",
      note: "punch-ins + label",
      src: "demo:видео: punch-in",
      duration: 2.6,
      zooms: [
        { at: 0.7, scale: 1.35, x: 0.5, y: 0.4 },
        { at: 1.4, scale: 1.8, x: 0.55, y: 0.45 },
        { at: 2.1, scale: 1 },
      ],
      overlays: [{ type: "label", text: "04 / punch-in", y: 0.14, at: 0 }],
    },
    {
      type: "video",
      note: "freeze frame",
      src: "demo:видео: freeze",
      duration: 2.8,
      freeze: { at: 1.0, label: "05 / freeze:\nона ещё *не знает*", style: "orange" },
      sfx: [{ at: 1.0, sfx: "scratch", volume: 0.8 }],
    },
    {
      type: "screen",
      note: "phone + zoom + cursor",
      src: "demo:screen recording",
      device: "phone",
      duration: 2.8,
      zooms: [{ at: 1.2, scale: 1.6, y: 0.3, duration: 0.35 }],
      overlays: [
        { type: "label", text: "06 / screen: phone", y: 0.1, at: 0 },
        { type: "cursor", x: 0.7, y: 0.75, toX: 0.48, toY: 0.42, click: true, at: 0.2, duration: 1.0 },
        { type: "notification", app: "Instagram", title: "3 просмотра", body: "двое из них — я", at: 1.6 },
      ],
      sfx: [{ at: 0.85, sfx: "click", volume: 0.7 }, { at: 1.6, sfx: "notification", volume: 0.6 }],
    },
    {
      type: "screen",
      note: "laptop",
      src: "demo:laptop screen",
      device: "laptop",
      bg: "paper",
      duration: 2.0,
      transition: "whip",
      overlays: [{ type: "label", text: "07 / screen: laptop", y: 0.2, at: 0 }],
      sfx: [{ at: 0, sfx: "whoosh", volume: 0.6 }],
    },
    {
      type: "image",
      note: "screenshot annotations",
      src: "demo:скриншот",
      duration: 2.8,
      overlays: [
        { type: "label", text: "08 / annotate", y: 0.12, at: 0 },
        { type: "highlight", x: 0.5, y: 0.52, w: 640, h: 90, at: 0.3 },
        { type: "circle", x: 0.5, y: 0.52, w: 700, h: 220, at: 0.8 },
        { type: "arrow", x: 0.25, y: 0.78, toX: 0.4, toY: 0.6, at: 1.2 },
        { type: "hand", text: "вот тут\nя плакала", x: 0.3, y: 0.85, at: 1.4 },
      ],
      sfx: [{ at: 0.8, sfx: "pop", volume: 0.5 }],
    },
    {
      type: "meme",
      note: "meme card",
      src: "demo:мем",
      caption: "09 / meme: я, когда AI\nговорит «готово»",
      top: "всё работает",
      bottom: "(ничего не работает)",
      duration: 2.6,
      transition: "drop",
      sfx: [{ at: 0, sfx: "bonk", volume: 0.6 }],
    },
    {
      type: "split",
      note: "expectation vs reality",
      a: { src: "demo:ожидание", label: "10 / ожидание" },
      b: { src: "demo:реальность", label: "*реальность*" },
      revealB: 0.9,
      duration: 2.6,
      sfx: [{ at: 0.9, sfx: "impact", volume: 0.5 }],
    },
    {
      type: "beat",
      note: "silence + audio cut",
      text: "11 / beat:\n(тишина — тоже звук)",
      duration: 1.2,
    },
    {
      type: "video",
      note: "stamp + shake + error",
      src: "demo:видео: провал",
      duration: 2.6,
      shakes: [{ at: 0.5, duration: 0.4, intensity: 1 }],
      overlays: [
        { type: "error", title: "build.log", body: "Build failed.\n*Again.*", buttons: ["Плакать", "OK"], at: 0, duration: 0.5 },
        { type: "stamp", text: "FAIL", y: 0.45, at: 0.5 },
        { type: "progress", label: "загрузка мотивации", from: 0, to: 12, y: 0.75, at: 0.9 },
      ],
      sfx: [{ at: 0, sfx: "error", volume: 0.5 }, { at: 0.5, sfx: "impact", volume: 0.7 }],
    },
    {
      type: "text",
      note: "lines + zoom in",
      kicker: "13 / text: lines",
      lines: ["Вывод:", "_я всё ещё_", "*не программист*"],
      animate: "lines",
      duration: 2.8,
      transition: "zoom",
      overlays: [{ type: "counter", text: "ДЕНЬ 47", x: 0.22, y: 0.14 }],
    },
    {
      type: "video",
      note: "лицо в окне → полный кадр",
      src: "demo:лицо в окне",
      duration: 3.0,
      window: { width: 0.84, aspect: 1.25, y: 0.4, growAt: 1.8, growDuration: 0.25 },
      overlays: [{ type: "label", text: "14 / окно → полный кадр", y: 0.12, duration: 1.8 }],
      sfx: [{ at: 1.8, sfx: "thud", volume: 0.6 }],
    },
    {
      type: "video",
      note: "ч/б с середины сцены",
      src: "demo:ч/б кадр",
      duration: 2.4,
      mono: { from: 0.8 },
      overlays: [
        { type: "label", text: "15 / ч/б с 0.8 с", y: 0.12 },
        { type: "hand", text: "сомнение", x: 0.5, y: 0.75, at: 0.8, color: "orange" },
      ],
      sfx: [{ at: 0.8, sfx: "drone", volume: 0.7 }],
    },
    {
      type: "video",
      note: "цифра-глава",
      src: "demo:глава",
      duration: 2.4,
      overlays: [
        { type: "chapter", text: "1.", aside: "(и самая _главная_)", x: 0.38, y: 0.32 },
        { type: "label", text: "16 / chapter", y: 0.88 },
      ],
      sfx: [{ at: 0, sfx: "impact", volume: 0.6 }],
    },
  ],
});
